In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_json('https://github.com/sukhioo7/dataset/blob/main/Animie%20dataset/data.json?raw=true')

In [3]:
df

,mal_id,titles,type,source,episodes,rating,score,scored_by,rank,popularity,members,favorites,synopsis,studios,genres,themes
0,1550,"[Attack No.1, ]",TV,Manga,104.0,PG-13 - Teens 13 or older,7.07,4117.0,4124.0,6406,9979,72,Kozue is a middleschool girl and enthusiastic ...,Tokyo Movie Shinsha,"[Drama, Sports]",[Team Sports]
1,2406,"[Sazae-san, Mrs. Sazae]",TV,4-koma manga,NaN,G - All Ages,6.14,1869.0,9126.0,6890,8403,38,The main character is a mother named Sazae-san...,Eiken,"[Comedy, Slice of Life]",[]
2,9895,"[The Bathroom, ]",Movie,Original,1.0,R - 17+ (violence & profanity),4.22,1003.0,13223.0,11636,1779,0,A surrealistic short from minimalist cartoonis...,Kuri Jikken Manga Koubou,"[Avant Garde, Comedy]",[]
3,9163,"[Attack No.1 (1970), ]",Movie,Unknown,1.0,PG-13 - Teens 13 or older,6.39,444.0,7795.0,12299,1410,3,"The first recap film of Attack No.1 , it cover...",,"[Drama, Sports]",[Team Sports]
4,7259,"[Kenju Giga, Anthropo-Cynical Farce]",Movie,Original,1.0,PG-13 - Teens 13 or older,4.92,595.0,12800.0,12805,1206,0,"A dog race is interrupted by a ringmaster, who...",,[],"[Parody, Psychological]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5051,56230,"[Jiisan Baasan Wakagaeru, Grandpa and Grandma ...",TV,Web manga,11.0,PG-13 - Teens 13 or older,7.07,9411.0,4141.0,2429,77998,268,Shouzou and Ine Saitou have been happily marri...,Gekkou,"[Comedy, Romance, Supernatural]",[]
5052,56923,[Lv2 kara Cheat datta Motoyuusha Kouho no Matt...,TV,Light novel,12.0,PG-13 - Teens 13 or older,7.02,10747.0,4349.0,2460,76187,288,The Magical Kingdom of Klyrode summons hundred...,J.C.Staff,"[Adventure, Fantasy, Romance]",[Isekai]
5053,53835,"[Unnamed Memory, Unnamed Memory]",TV,Light novel,12.0,PG-13 - Teens 13 or older,7.25,8563.0,3091.0,2463,76018,243,"As a young boy, Prince Oscar Lyeth Increatos L...",ENGI,"[Adventure, Fantasy, Romance]",[]
5054,52995,[Arifureta Shokugyou de Sekai Saikyou Season 3...,TV,Light novel,NaN,PG-13 - Teens 13 or older,NaN,NaN,NaN,2482,75338,538,Third season of Arifureta Shokugyou de Sekai S...,asread.,"[Action, Adventure, Fantasy]","[Harem, Isekai]"
5055,37885,"[Super Dragon Ball Heroes, ]",ONA,Game,NaN,PG-13 - Teens 13 or older,5.35,28936.0,12121.0,2488,75034,239,"In May 2018, V-Jump announced the promotional ...",Dimps,"[Action, Comedy, Fantasy]","[Martial Arts, Super Power]"

In [4]:
df.head()

,mal_id,titles,type,source,episodes,rating,score,scored_by,rank,popularity,members,favorites,synopsis,studios,genres,themes
0,1550,"[Attack No.1, ]",TV,Manga,104.0,PG-13 - Teens 13 or older,7.07,4117.0,4124.0,6406,9979,72,Kozue is a middleschool girl and enthusiastic ...,Tokyo Movie Shinsha,"[Drama, Sports]",[Team Sports]
1,2406,"[Sazae-san, Mrs. Sazae]",TV,4-koma manga,NaN,G - All Ages,6.14,1869.0,9126.0,6890,8403,38,The main character is a mother named Sazae-san...,Eiken,"[Comedy, Slice of Life]",[]
2,9895,"[The Bathroom, ]",Movie,Original,1.0,R - 17+ (violence & profanity),4.22,1003.0,13223.0,11636,1779,0,A surrealistic short from minimalist cartoonis...,Kuri Jikken Manga Koubou,"[Avant Garde, Comedy]",[]
3,9163,"[Attack No.1 (1970), ]",Movie,Unknown,1.0,PG-13 - Teens 13 or older,6.39,444.0,7795.0,12299,1410,3,"The first recap film of Attack No.1 , it cover...",,"[Drama, Sports]",[Team Sports]
4,7259,"[Kenju Giga, Anthropo-Cynical Farce]",Movie,Original,1.0,PG-13 - Teens 13 or older,4.92,595.0,12800.0,12805,1206,0,"A dog race is interrupted by a ringmaster, who...",,[],"[Parody, Psychological]"

In [5]:
df.isnull().sum()

mal_id          0
titles          0
type            1
source          0
episodes      517
rating         34
score         239
scored_by     239
rank          270
popularity      0
members         0
favorites       0
synopsis       47
studios         0
genres          0
themes          0
dtype: int64

In [6]:
df.describe()

,mal_id,episodes,score,scored_by,rank,popularity,members,favorites
count,5056.000000,4539.000000,4817.000000,4.817000e+03,4786.000000,5056.000000,5.056000e+03,5056.000000
mean,13436.020372,18.509363,7.029498,1.229240e+05,4862.653155,5827.900514,2.187640e+05,6901.799248
std,16425.207730,62.329765,0.931790,2.749153e+05,4240.655440,5668.755969,4.544549e+05,32039.765112
min,1.000000,1.000000,2.000000,1.050000e+02,1.000000,1.000000,5.100000e+01,0.000000
25%,1427.500000,1.000000,6.460000,1.723000e+03,1320.000000,1049.750000,3.564000e+03,5.000000
50%,4526.000000,12.000000,7.110000,1.797500e+04,3877.500000,3843.000000,3.354050e+04,90.000000
75%,23347.500000,23.000000,7.670000,1.182690e+05,7454.000000,9501.500000,2.314838e+05,1257.000000
max,58391.000000,1787.000000,9.380000,2.795232e+06,20609.000000,26508.000000,3.943368e+06,225867.000000

In [7]:
df.dropna(inplace=True)

In [8]:
df.reset_index(inplace=True,drop=True)

In [9]:
 #Normalize text data#
df['synopsis'] = df['synopsis'].apply(lambda x: x.lower().replace('\n',' ').split())

In [10]:
df.head()

,mal_id,titles,type,source,episodes,rating,score,scored_by,rank,popularity,members,favorites,synopsis,studios,genres,themes
0,1550,"[Attack No.1, ]",TV,Manga,104.0,PG-13 - Teens 13 or older,7.07,4117.0,4124.0,6406,9979,72,"[kozue, is, a, middleschool, girl, and, enthus...",Tokyo Movie Shinsha,"[Drama, Sports]",[Team Sports]
1,9895,"[The Bathroom, ]",Movie,Original,1.0,R - 17+ (violence & profanity),4.22,1003.0,13223.0,11636,1779,0,"[a, surrealistic, short, from, minimalist, car...",Kuri Jikken Manga Koubou,"[Avant Garde, Comedy]",[]
2,9163,"[Attack No.1 (1970), ]",Movie,Unknown,1.0,PG-13 - Teens 13 or older,6.39,444.0,7795.0,12299,1410,3,"[the, first, recap, film, of, attack, no.1, ,,...",,"[Drama, Sports]",[Team Sports]
3,7259,"[Kenju Giga, Anthropo-Cynical Farce]",Movie,Original,1.0,PG-13 - Teens 13 or older,4.92,595.0,12800.0,12805,1206,0,"[a, dog, race, is, interrupted, by, a, ringmas...",,[],"[Parody, Psychological]"
4,2830,"[Chibikko Remi to Meiken Kapi, ]",Movie,Novel,1.0,G - All Ages,5.90,334.0,10228.0,13050,1125,1,"[based, on, sans, famille, by, hector, malot.,...",Toei Animation,"[Adventure, Drama, Slice of Life]",[]

In [11]:
df.columns

Index(['mal_id', 'titles', 'type', 'source', 'episodes', 'rating', 'score',
       'scored_by', 'rank', 'popularity', 'members', 'favorites', 'synopsis',
       'studios', 'genres', 'themes'],
      dtype='object')

In [12]:
anime_data = df[['mal_id', 'titles','score','synopsis', 'genres', 'themes' ]]

In [13]:
anime_data.head()

,mal_id,titles,score,synopsis,genres,themes
0,1550,"[Attack No.1, ]",7.07,"[kozue, is, a, middleschool, girl, and, enthus...","[Drama, Sports]",[Team Sports]
1,9895,"[The Bathroom, ]",4.22,"[a, surrealistic, short, from, minimalist, car...","[Avant Garde, Comedy]",[]
2,9163,"[Attack No.1 (1970), ]",6.39,"[the, first, recap, film, of, attack, no.1, ,,...","[Drama, Sports]",[Team Sports]
3,7259,"[Kenju Giga, Anthropo-Cynical Farce]",4.92,"[a, dog, race, is, interrupted, by, a, ringmas...",[],"[Parody, Psychological]"
4,2830,"[Chibikko Remi to Meiken Kapi, ]",5.90,"[based, on, sans, famille, by, hector, malot.,...","[Adventure, Drama, Slice of Life]",[]

In [14]:
anime_data['titles'].apply(lambda x: ' '.join(x))

0                                            Attack No.1
1                                           The Bathroom
2                                     Attack No.1 (1970)
3                       Kenju Giga Anthropo-Cynical Farce
4                           Chibikko Remi to Meiken Kapi
                              ...
4081             Sentai Daishikkaku Go! Go! Loser Ranger!
4082    Maou no Ore ga Dorei Elf wo Yome ni Shitanda g...
4083    Jiisan Baasan Wakagaeru Grandpa and Grandma Tu...
4084    Lv2 kara Cheat datta Motoyuusha Kouho no Matta...
4085                        Unnamed Memory Unnamed Memory
Name: titles, Length: 4086, dtype: object

In [15]:
anime_data['titles'] = anime_data['titles'].apply(lambda x: x[0])

C:\Users\vansh\AppData\Local\Temp\ipykernel_33976\3769317530.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime_data['titles'] = anime_data['titles'].apply(lambda x: x[0])

In [16]:
anime_data['score'] = anime_data['score'].apply(lambda x:[str(x)])

C:\Users\vansh\AppData\Local\Temp\ipykernel_33976\2136853907.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime_data['score'] = anime_data['score'].apply(lambda x:[str(x)])

In [17]:
def genre_space(value):
    temp = []
    for genre in value:
        genre = genre.replace(' ','')
        temp.append(genre)
    return temp

In [18]:
genre_space(["Avant Garde", "Comedy"])

['AvantGarde', 'Comedy']

In [19]:
anime_data['genres'] = anime_data['genres'].apply(genre_space)

C:\Users\vansh\AppData\Local\Temp\ipykernel_33976\4083625022.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime_data['genres'] = anime_data['genres'].apply(genre_space)

In [20]:
anime_data['themes'] = anime_data['themes'].apply(genre_space)

C:\Users\vansh\AppData\Local\Temp\ipykernel_33976\3048737251.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime_data['themes'] = anime_data['themes'].apply(genre_space)

In [21]:
anime_data['Tag'] = anime_data['score'] + anime_data['genres'] + anime_data['themes'] + anime_data['synopsis']

C:\Users\vansh\AppData\Local\Temp\ipykernel_33976\3248858356.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime_data['Tag'] = anime_data['score'] + anime_data['genres'] + anime_data['themes'] + anime_data['synopsis']

In [22]:
anime_data = anime_data[['mal_id','titles','Tag']]

In [23]:
anime_data.to_csv('Anime_data.csv')

In [24]:
anime_data.head()

,mal_id,titles,Tag
0,1550,Attack No.1,"[7.07, Drama, Sports, TeamSports, kozue, is, a..."
1,9895,The Bathroom,"[4.22, AvantGarde, Comedy, a, surrealistic, sh..."
2,9163,Attack No.1 (1970),"[6.39, Drama, Sports, TeamSports, the, first, ..."
3,7259,Kenju Giga,"[4.92, Parody, Psychological, a, dog, race, is..."
4,2830,Chibikko Remi to Meiken Kapi,"[5.9, Adventure, Drama, SliceofLife, based, on..."

In [25]:
anime_data['Tag'] = anime_data['Tag'].apply(lambda x:' '.join(x).lower())

In [26]:
from nltk.stem.porter import PorterStemmer

stemming = PorterStemmer()

In [27]:
def stemming_words(items):
  temp_lst = []
  items = items.split()
  for word in items:
    temp_lst.append(stemming.stem(word))
  return temp_lst

In [28]:
anime_data['Tag'] =anime_data['Tag'].apply(stemming_words)

In [29]:
anime_data['Tag'] = anime_data['Tag'].apply(lambda item: ' '.join(item))

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

# TF-IDF Vectorization for 'synopsis'
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
tfidf_matrix = tfidf.fit_transform(anime_data['Tag'])

In [31]:
tfidf_matrix = tfidf_matrix.toarray()

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

similar_matrix = cosine_similarity(tfidf_matrix)

In [33]:
sorted(similar_matrix[0],reverse=True)[1:5]

[0.8705344141755824,
 0.5000922413969751,
 0.3539743453923083,
 0.3402295221371112]

In [34]:
def recommend(anime):
    try:
        index = anime_data[anime_data['titles'] == anime].index[0]
        distances = sorted(list(enumerate(similar_matrix[index])),
                           reverse=True,key = lambda x: x[1])
        for i in distances[1:6]:
            print(anime_data.iloc[i[0]]['titles'])
    except:
        records = anime_data[anime_data['titles'].str.contains(anime)]['titles']
        print(records)
        index = int(input('Enter Index of the Anime : '))
        distances = sorted(list(enumerate(similar_matrix[index])),
                           reverse=True,key = lambda x: x[1])
        for i in distances[1:6]:
            print(anime_data.iloc[i[0]]['titles'])

In [ ]:
recommend('One')

683                                     Onegai! Samia Don
1331                Uchida Shungicu no Noroi no One-Piece
1776                    One Piece: Taose! Kaizoku Ganzack
1882    One Piece: Kinkyuu Kikaku One Piece Kanzen Kou...
1893                                   One Piece Movie 01
1958              One Piece: Umi no Heso no Daibouken-hen
1969       One Piece Movie 02: Nejimaki-jima no Daibouken
1973                   One Piece: Jango no Dance Carnival
2050                                       Onegai☆Teacher
2054    One Piece Movie 03: Chinjuu-jima no Chopper Ou...
2058                        One Piece: Yume no Soccer Ou!
2121                    Onegai☆Teacher: Himitsu na Futari
2136               One Piece Movie 04: Dead End no Bouken
2175    One Piece: Oounabara ni Hirake! Dekkai Dekkai ...
2182                                         Onegai☆Twins
2223                One Piece Movie 05: Norowareta Seiken
2228                 One Piece: Mezase! Kaizoku Yakyuu Ou
2258                      Onegai☆Twins: Natsu wa Owaranai
2307    One Piece Movie 06: Omatsuri Danshaku to Himit...
2388    One Piece: Nenmatsu Tokubetsu Kikaku! Mugiwara...
2396     One Piece Movie 07: Karakuri-jou no Mecha Kyohei
2481    One Piece Movie 08: Episode of Alabasta - Saba...
2575    One Piece Movie 09: Episode of Chopper Plus - ...
2635                                             One Outs
2723                         One Piece Film: Strong World
2775               One Piece Film: Strong World Episode 0
2845                         One Piece 3D: Mugiwara Chase
3004                                    One Piece Film: Z
3120                                     Oneechan ga Kita
3259                                        One Punch Man
3268                          One Punch Man: Road to Hero
3269                               One Punch Man Specials
3582                             One Punch Man 2nd Season
3625                         One Piece Movie 14: Stampede
3891                                  One Piece Film: Red
Name: titles, dtype: object

In [ ]:
import pickle as pk

In [ ]:
pk.dump(similar_matrix,open('similar_anime.pkl','wb'))

In [ ]:
anime_data['titles'].values